Repository AADILcrackstheweb/Spaceshooterv2, pull requests merged in 2022-10, with the labels that each got.

#6 Create basicpolygonpygame.py
  basicpolygonpygame.py
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2022

#7 Update basicpolygonpygame.py
  basicpolygonpygame.py
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2022

#9 Added instructions on how to play
  README.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2022

#8 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2022
